name: haweli
description: A restaurant app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  sembast: ^2.1.1
  #stripe_payment: ^1.0.5
  cupertino_icons: ^0.1.2
  #stripe_sdk: ^2.4.2
  flushbar: ^1.5.0
  provider: ^3.1.0+1
  intl: ^0.16.0
  datetime_picker_formfield:
  flutter_time_picker_spinner: ^1.0.6
  graphql_flutter: ^2.0.0
  shared_preferences:
  scoped_model: ^1.0.1
  sqflite: ^1.1.7+3
  localstorage: ^3.0.0
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

