name: haweli
description: A restaurant app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  graphql_flutter: ^2.1.0
  splashscreen: ^1.2.0
  #stripe_payment: ^1.0.5
  cupertino_icons: ^0.1.2
  #stripe_sdk: ^2.4.2
  provider: ^3.1.0+1
  intl: ^0.16.0
  #datetime_picker_formfield:
  flutter_time_picker_spinner: ^1.0.6
  shared_preferences:
  scoped_model: ^1.0.1
  sqflite:
  localstorage: ^3.0.0
  flutter_stripe_payment: ^0.0.7
  path:
  fluttertoast: ^3.1.3
  flutter_signin_button: ^1.0.0
  progress_dialog: ^1.2.0
  firebase_messaging: ^5.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

